[env:esp32dev]
platform = espressif32@6.0.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    electroniccats/MPU6050;
    https://github.com/RoboCore/RoboCore_Vespa